stages:
    - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test-dcl2-unit:
    stage: test
    image: registry.gitlab.com/project-deadlock/libdeadcom/deadcom-tester:latest
    script:
        - make run-dcl2unit-tests

test-dcl2-integration:
    stage: test
    image: registry.gitlab.com/project-deadlock/libdeadcom/deadcom-tester:latest
    script:
        - make run-dcl2intg-tests

test-leakypipe-unit:
    stage: test
    image: registry.gitlab.com/project-deadlock/libdeadcom/deadcom-tester:latest
    script:
        - make run-lpunit-tests

test-build-docs:
    stage: test
    image: python:3-alpine3.7
    script:
        - apk add --update doxygen make
        - pip install -r docs/requirements.txt
        - cd docs && make html
